### PR TITLE
Ability to start the week from a specific day

### PR DESCRIPTION
**Pull request by itsmichaeldiego**
@sjlu First of all, thank you so much for the library that you've created, it has been super useful on my end.

On my case, I would like the week to start from a specific day of the week, this changes handles that.

### CODE REVIEW

**Comment by itsmichaeldiego** [comment]
@sjlu Have you had the chance to see this?

**Comment by sjlu** [comment]
Hmm, this definitely did not hit my inbox in 2018

**Comment by itsmichaeldiego** [comment]
Thanks @sjlu, feel free to test it and let me know if there's any issue, I am happy to assist.

**Comment by sjlu** [comment]
Made a release in 0.2.1

**Pull request merged**
