### PR TITLE
Fix deprecated moment usage.

### PR DESCRIPTION
**Pull request by eanplatter**
Hi @sjlu! 

This is an awesome lib, thanks for making it! Abstracts the harder part of making a calendar UI :D 

While using it I got a moment deprecation error for the `add` and `subtract` methods, so I thought I could help out! 

Let me know if it wasn't necessary you can just close the PR if that is the case! I wasn't exactly sure.

Thanks!

_more info on the deprecation: http://momentjs.com/guides/#/warnings/add-inverted-param/_

### CODE REVIEW

**Comment by sjlu** [comment]
Yes, this looks fine. I'd say that this lib is _really_ old though and probably requires much more love.

**Comment by eanplatter** [comment]
Ha, hey if it isn't broken, don't fix it :P

**Comment by sjlu** [comment]
Ha, yes. I use this in a couple of places too. I also bumped momentjs and removed lodash as a dep. Bumped to 0.1.0

**Comment by eanplatter** [comment]
Wahoo minor version! Thanks I can update now.

**Pull request merged**
